# Generated by Django 5.1.7 on 2025-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv jahte')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena (€)')),
                ('year', models.IntegerField(verbose_name='Godina proizvodnje')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dužina (m)')),
                ('yacht_type', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10, verbose_name='Tip jahte')),
                ('description', models.TextField(blank=True, verbose_name='Opis jahte')),
                ('image', models.ImageField(blank=True, null=True, upload_to='yachts/', verbose_name='Slika jahte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum objave')),
            ],
        ),
    ]
