# Generated by Django 5.1.7 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yacht',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='yacht_type',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=10, verbose_name='Tip jahte'),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Godina proizvodnje'),
        ),
    ]
