# Generated by Django 5.1.7 on 2025-04-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_yacht_published_yacht_slug_alter_yacht_yacht_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, default='+381 60 111 111', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='contact@yacht.rs', max_length=254, null=True)),
                ('instagram_link', models.CharField(blank=True, default='www.instagram.com', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='defautl address', max_length=255, null=True)),
            ],
        ),
    ]
