# Generated by Django 5.1.7 on 2025-04-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yacht_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.yacht')),
            ],
        ),
    ]
