# Generated by Django 5.1.7 on 2025-04-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_yacht_created_at_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='YachtCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='website.yacht')),
            ],
        ),
        migrations.CreateModel(
            name='YachtSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.yacht')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='YachtSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='website.yachtsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='YachtDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.yachtsubsection')),
            ],
        ),
    ]
