# Generated by Django 5.1.7 on 2025-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_yachtcharacteristic_yachtsection_yachtsubsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yachtcharacteristic',
            name='name',
            field=models.CharField(choices=[('model', 'Model'), ('length', 'Length (m)'), ('beam', 'Beam (m)'), ('draft', 'Draft (m)'), ('weight', 'Weight (kg)'), ('propulsion', 'Propulsion'), ('fuel_tank', 'Fuel Tank (l)'), ('water_tank', 'Water Tank (l)'), ('cabins', 'Number of Cabins'), ('speed', 'Speed')], max_length=100),
        ),
    ]
