# Generated by Django 5.1.7 on 2025-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_yachtcharacteristic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='yachtcharacteristic',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
