# Generated by Django 5.1.7 on 2025-04-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_yachtcharacteristic_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='length',
        ),
        migrations.RemoveField(
            model_name='yacht',
            name='year',
        ),
        migrations.CreateModel(
            name='SubSectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='website.sectiontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DetailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('subsection_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.subsectiontemplate')),
            ],
        ),
    ]
