# Generated by Django 5.1.7 on 2025-04-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_yachtsection_yachtsubsection_yachtdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YachtDetail',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='YachtSection',
            new_name='Section',
        ),
        migrations.RenameModel(
            old_name='YachtSubSection',
            new_name='SubSection',
        ),
    ]
