# Generated by Django 5.1.7 on 2025-04-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_yachtdetail_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yacht',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='yachtcharacteristic',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='yacht',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yachtcharacteristic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
