# Generated by Django 5.1.7 on 2025-04-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_yacht_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yachtcharacteristic',
            options={},
        ),
        migrations.RemoveField(
            model_name='yachtcharacteristic',
            name='order',
        ),
    ]
