# Generated by Django 5.1.7 on 2025-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_yachtcharacteristic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yachtcharacteristic',
            name='name',
            field=models.CharField(choices=[('model', 'MODEL'), ('length', 'DUŽINA(m)'), ('beam', 'ŠIRINA'), ('draft', 'GAZ (m)'), ('weight', 'TEŽINA (kg)'), ('propulsion', 'POGON'), ('fuel_tank', 'TANK GORIVA (l)'), ('water_tank', 'TANK VODE (l)'), ('cabins', 'BROJ KABINA'), ('speed', 'BRZINA')], max_length=100),
        ),
    ]
