# Generated by Django 5.1.7 on 2025-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_yachtcharacteristic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Cena (€)'),
        ),
        migrations.AlterField(
            model_name='yachtcharacteristic',
            name='name',
            field=models.CharField(choices=[('model', 'MODEL'), ('length', 'DUŽINA(m)'), ('beam', 'ŠIRINA'), ('draft', 'GAZ (m)'), ('weight', 'TEŽINA (t)'), ('propulsion', 'POGON'), ('fuel_tank', 'TANK GORIVA (l)'), ('water_tank', 'TANK VODE (l)'), ('cabins', 'BROJ KABINA'), ('speed', 'BRZINA')], max_length=100),
        ),
    ]
